print("First Time Stamp")
FTH=int(input("Enter Hours:"))
FTM=int(input("Enter Minutes:"))
FTS=int(input("Enter Seconds:"))
FTHinsec=int(FTH * 60 * 60)
FTMinsec=int(FTM * 60)
FTSinsectotal=int(FTHinsec + FTMinsec + FTS)
#rint(FTHinsec)
print("Second Time Stamp")
STH=int(input("Enter Hours:"))
STM=int(input("Enter Minutes:"))
STS=int(input("Enter Seconds:"))
STHinsec=int(STH * 60 * 60)
STMinsec=int(STM * 60)
STSinsectotal=int(STHinsec + STMinsec + STS)
diff=int(STSinsectotal - FTSinsectotal)
print(diff)